# Generated by Django 5.2.7 on 2025-11-06 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workstation',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
