# Generated by Django 5.2.7 on 2025-11-21 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='corrective_action',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='preventive_action',
            field=models.TextField(blank=True, null=True),
        ),
    ]
